# Generated by Django 3.0.6 on 2020-05-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200516_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/uploads/profile_pic/default.jpg', upload_to='uploads/profile_pics'),
        ),
    ]
