# Generated by Django 3.0.6 on 2020-05-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20200516_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='uploads/profile_pics/default.jpg', upload_to='uploads/profile_pics'),
        ),
    ]
